name: spread
adopt-info: spread
summary: Convenient full-system test (task) distribution
description: |
    Spread is a plesant way distribute full-system integration tests and
    similar tasks. A few simple and concrete concepts that are fun to play
    with and fix the exact piece missing in the puzzle. It's not Jenkins,
    it's not Travis, it's not a library, not a language, and it's not even
    specific to testing. It's a simple way to express what to run and
    where, what to do before and after it runs, and how to duplicate jobs
    with minor variations without copy & paste.

confinement: strict
grade: stable
base: core22

plugs:
  dot-spread:
    interface: personal-files
    read:
      - $HOME/.spread
    write:
      - $HOME/.spread
  dot-gcloud:
    interface: personal-files
    read:
      - $HOME/.config/gcloud
apps:
    spread:
        command: bin/spread
        plugs:
          - home
          - network
          - network-bind
          - dot-spread
          - dot-gcloud

parts:
    spread:
        plugin: go
        source: .
        build-packages: [git]
        build-snaps: [go]
        override-pull: |
          snapcraftctl pull
          snapcraftctl set-version "$(date +"%Y.%m.%d").g$(git describe --always)"
