name: Test spread

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master


jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          spread google:

      - name: Discard spread workers
        if: always()
        run: |
          shopt -s nullglob
          for r in .spread-reuse.*.yaml; do
            spread -discard -reuse-pid="$(echo "$r" | grep -o -E '[0-9]+')"
          done

  action-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Spread
        uses: ./
        id: install-spread
        with:
          ref: ${{ github.sha }}

      - name: Test the spread installation
        run: |
          echo "Spread path: ${{ steps.install-spread.outputs.path }}"
          spread -list

