name: Test spread

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master


jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          spread google:ubuntu-20.04-64: google:ubuntu-22.04-64-devstack:tests/openstack

      - name: Discard spread workers
        if: always()
        run: |
          shopt -s nullglob
          for r in .spread-reuse.*.yaml; do
            spread -discard -reuse-pid="$(echo "$r" | grep -o -E '[0-9]+')"
          done
